FROM python:3.10-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && \
    apt-get install -y netcat-openbsd ;\
    apt-get install -y gettext ;\
    apt-get install -y httpie ;\
    apt-get install -y python3-flask ; 

RUN mkdir /code
WORKDIR /code

COPY ./server.py .

ENTRYPOINT ["python", "./server.py"]