# Generated by Django 5.1.1 on 2024-10-07 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meetupicalmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupicalmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='meetupicalmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
