# Generated by Django 5.1.1 on 2024-10-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_meetupicalmodel_id_alter_meetupicalmodel_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupicalmodel',
            name='author',
        ),
        migrations.AlterField(
            model_name='meetupicalmodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
